base_url = "https://blog.changki123.click"
title = "changki123's blog"
description = "Infrastructure Engineer's Tech Blog"
compile_sass = true
build_search_index = true

theme = "terminimal"

taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true},
]

[markdown]
highlight_code = true

[extra]
# terminimal 테마 설정
accent_color = "orange"
logo_text = "changki123"
